[package]
name = "hello-wasm"
version = "0.1.0"
authors = ["fizban007 <fizban007@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
crate-type = ["cdylib"]

[dependencies]
wasm-bindgen = "0.2"
js-sys = "0.3"

[profile.release]
debug = true
lto = true
